### PR TITLE
Gracefully handle resources deleted manually

### LINKED ISSUE #77: `terraform refresh` fails with 404 when an Auth0 resource was destroyed manually
`terraform refresh` fails with 404 when some of the managed auth0 resources have been manually destroyed. `apply` and `destroy` commands will also fail due to the same reason and the only way to recover is to manually remove the affected resources from the state.
Other providers deal with such issues by silently removing the resources which are no longer present from the state during refresh.

Example:

```
$  terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + auth0_resource_server.my_resource_server
      id:                                              <computed>
      allow_offline_access:                            "true"
      identifier:                                      "https://api.example.com"
      name:                                            "Example Resource Server (Managed by Terraform)"
      scopes.#:                                        "2"
      scopes.0.description:                            "Create foos"
      scopes.0.value:                                  "create:foo"
      scopes.1.description:                            "Create bars"
      scopes.1.value:                                  "create:bar"
      signing_alg:                                     "RS256"
      skip_consent_for_verifiable_first_party_clients: "true"
      token_lifetime:                                  "8600"


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

auth0_resource_server.my_resource_server: Creating...
  allow_offline_access:                            "" => "true"
  identifier:                                      "" => "https://api.example.com"
  name:                                            "" => "Example Resource Server (Managed by Terraform)"
  scopes.#:                                        "0" => "2"
  scopes.0.description:                            "" => "Create foos"
  scopes.0.value:                                  "" => "create:foo"
  scopes.1.description:                            "" => "Create bars"
  scopes.1.value:                                  "" => "create:bar"
  signing_alg:                                     "" => "RS256"
  skip_consent_for_verifiable_first_party_clients: "" => "true"
  token_lifetime:                                  "" => "8600"
auth0_resource_server.my_resource_server: Creation complete after 0s (ID: 5c644c21c96fc41a99e3912c)
```

Destroy the "Example Resource Server (Managed by Terraform)" manually via the Auth0 UI

```
$ terraform refresh
auth0_resource_server.my_resource_server: Refreshing state... (ID: 5c644c21c96fc41a99e3912c)

Error: Error refreshing state: 1 error(s) occurred:

* auth0_resource_server.my_resource_server: 1 error(s) occurred:

* auth0_resource_server.my_resource_server: auth0_resource_server.my_resource_server: 404 Not Found: The resource server does not exist
```

### PR DESCRIPTION
**Pull request by mmindenhall**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #77

Changes proposed in this pull request:

* Fixes all resources to handle the case where a resource created by this provider is deleted in some other way (e.g., manually in the console, or via the API outside of this provider).

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX

...
```
TODO

I tested this manually with the Resource Server, Client, and Client Grant resources.  I'm not sure how to create an automated test for this functionality, and have run out of time available to spend on this during my holiday break.  But I wanted to at least get the code changes in for others to look at.  These changes follow the patterns suggested when [reading a resource](https://www.terraform.io/docs/extend/writing-custom-providers.html#implementing-read) and [destroying a resource](https://www.terraform.io/docs/extend/writing-custom-providers.html#implementing-destroy).

### CODE REVIEW

File: auth0/resource_auth0_client.go [hunk 1]
```diff
@@ -465,6 +466,12 @@ func createClient(d *schema.ResourceData, m interface{}) error {
...
 	c, err := api.Client.Read(d.Id())
+
+	if err != nil && strings.HasPrefix(err.Error(), "404") {
+		d.SetId("")
+		return nil
+	}
+
 	if err != nil {
 		return err
 	}
```
Comment (alexkappa) [inline auth0/resource_auth0_client.go]: Checking for the error string is not a safe way to check this type of error as its not guaranteed to always be present.

We should instead type assert whether `err` is a [`management.Error`](https://github.com/go-auth0/auth0/blob/master/management/management.go#L274-L277) - which it should be - and check the status from that.

```
e, err := api. Client.Read(d.Id())
if err != nil {
	if mErr, ok := err.(management.Error); ok {
		if mErr.Status() == http.StatusNotFound {
			d.SetId("")
			return nil
		}
	}
	return err
}
```

Comment (mmindenhall) [reply auth0/resource_auth0_client.go]: Yes...I looked at the unexported `managementError` struct, and thought the best we could do was to read the status code from the string.  I missed the fact that the struct implements the exported `Error` interface.  I'll make that fix.

File: auth0/resource_auth0_custom_domain.go [hunk 2]
```diff
@@ -6,6 +6,7 @@ import (
 
 	"gopkg.in/auth0.v2"
 	"gopkg.in/auth0.v2/management"
+	"net/http"
```
Comment (alexkappa) [inline auth0/resource_auth0_custom_domain.go]: Could you move this import statement on top? It should be done as the `goimports` tool with stdlib first, then third party and finally first party. For example:

```
import (
	"net/http"

	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/helper/validation"

	"gopkg.in/auth0.v2"
	"gopkg.in/auth0.v2/management"
)
```
